apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-config-contracts
  namespace: nks-statistikk
data:
  config.yaml: |
    type: bigquery
    name: nks-statistikk-bigquery
    connection:
      use_context_auth: true
      project_id: nks-statistikk-prod-80c9