apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: nks-statistikk
data:
  oppgavestatistikk.yaml: |
    filter nks_oppgave_dag_hist [begrenset]:
      where: dato > CURRENT_DATE() - 7

    filter nks_oppgave_dag_hist [begrenset]:
      where: dato > CURRENT_DATE() - 7
  
   checks for innsyn_oppgave_dag_hist [begrenset]:
      - freshness(dato) < 1d:
          name: "Sjekker om data er mer enn ett døgn gamle"

    checks for innsyn_oppgave_dag_hist [begrenset]:
      - freshness(dato) < 1d:
          name: "Sjekker om data er mer enn ett døgn gamle"

  boost_data.yaml: |
    filter boost_chat_hour_raw [begrenset]:
      where: period > CURRENT_DATE() - 7

    filter boost_chat_human_transfer_day_raw [begrenset]:
      where: period > CURRENT_DATE() - 7

    filter boost_chat_intents_day_raw [begrenset]:
      where: period > CURRENT_DATE() - 7
     
    checks for boost_chat_hour_raw [begrenset]:
      - freshness(period) < 1d: 
          name: "Sjekker om data er mer enn ett døgn gamle"

    checks for boost_chat_human_transfer_day_raw [begrenset]:
      - freshness(period) < 1d: 
          name: "Sjekker om data er mer enn ett døgn gamle"
          
    checks for boost_chat_intents_day_raw [begrenset]:
      - freshness(period) < 1d: 
          name: "Sjekker om data er mer enn ett døgn gamle"
  
  sf_chat_data.yaml: |
    filter chat_enhet [begrenset]:
      where: date > CURRENT_DATE() - 7

    filter chat_kanalstatistikk [begrenset]:
      where: date > CURRENT_DATE() - 7
     
    checks for chat_enhet [begrenset]:
      - freshness(date) < 1d: 
          name: "Sjekker om data er mer enn ett døgn gamle"

    checks for chat_kanalstatistikk [begrenset]:
      - freshness(date) < 1d: 
          name: "Sjekker om data er mer enn ett døgn gamle"
          
    checks for chat_concurrency:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN MAX(date) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM chat_concurrency 
            WHERE date > CURRENT_DATE() - 7
  
  sf_sto_data.yaml: |
    filter sto_enhet [begrenset]:
      where: date > CURRENT_DATE() - 7

    filter sto_kanalstatistikk [begrenset]:
      where: date > CURRENT_DATE() - 7

    filter case_milestone [begrenset]:
      where: start_date > CURRENT_DATE() - 7
     
    checks for sto_enhet [begrenset]:
      - freshness(date) < 1d: 
          name: "Sjekker om data er mer enn ett døgn gamle"

    checks for sto_kanalstatistikk [begrenset]:
      - freshness(date) < 1d:
          name: "Sjekker om data er mer enn ett døgn gamle"
          
    checks for case_milestone [begrenset]:
      - freshness(start_date) < 1d:
          name: "Sjekker om data er mer enn ett døgn gamle"
          
    checks for sto_beholdning:
      - freshness(dato_tid) < 1d:
          name: "Sjekker om data er mer enn ett døgn gamle"
          
    checks for user:
      - freshness(last_til_bq_ts) < 1d: 
          name: "Sjekker om data er mer enn ett døgn gamle"
          
  sf_kunnskapsbase.yaml: |
    filter artikkelvisninger_daglig_snapshot [begrenset]:
      where: Date > CURRENT_DATE() - 7
     
    checks for artikkelvisninger_daglig_snapshot [begrenset]:
      - freshness(Date) < 1d: 
          name: "Sjekker om data er mer enn ett døgn gamle"
          
    checks for kunnskapsartikler:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN DATE(MAX(load_to_bq_ts)) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM kunnskapsartikler
          
  stillingsregistrering.yaml: |     
    checks for stilling_agg_dag:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN MAX(dato) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM stilling_agg_dag 
            WHERE dato > CURRENT_DATE() - 7
          
    checks for stilling_beholdning:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN DATE(MAX(last_updated_ts)) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM stilling_beholdning
  
  samtalereferat_data.yaml: |
    checks for topp_frekvens_intradag:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN MAX(dato) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM topp_frekvens_intradag 
            WHERE dato > CURRENT_DATE() - 7
          
    checks for topp_trend_intradag:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN MAX(dato) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM topp_trend_intradag 
            WHERE dato > CURRENT_DATE() - 7

    checks for alle_nks_referater:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN DATE(MAX(crm_registered_datetime_formula__c)) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM alle_nks_referater 
            WHERE crm_registered_datetime_formula__c > CURRENT_DATE() - 7

  tastevalg_agg_mnd.yaml: |
    checks for andre_familiehenvendelser:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN DATE(MAX(sist_oppdatert_tidspunkt)) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM andre_familiehenvendelser

    checks for arbeidsavklaringspenger:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN DATE(MAX(sist_oppdatert_tidspunkt)) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM arbeidsavklaringspenger

    checks for barnebidrag:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN DATE(MAX(sist_oppdatert_tidspunkt)) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM barnebidrag

    checks for barnebidrag_undermeny:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN DATE(MAX(sist_oppdatert_tidspunkt)) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM barnebidrag_undermeny

    checks for foreldrepenger:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN DATE(MAX(sist_oppdatert_tidspunkt)) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM foreldrepenger

    checks for jobbsoker:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN DATE(MAX(sist_oppdatert_tidspunkt)) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM jobbsoker
    
    checks for pleiepenger:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN DATE(MAX(sist_oppdatert_tidspunkt)) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM pleiepenger

    checks for sykepenger:
      - UpdatedOk > 0:
          name: "Sjekker om data er mer enn ett døgn gamle (hvis igår var hverdag)"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN EXTRACT(DAYOFWEEK FROM CURRENT_DATE())  in (1,2) THEN 2
                WHEN DATE(MAX(sist_oppdatert_tidspunkt)) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM sykepenger
