apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: nks-statistikk
data:
  oppgavestatistikk.yaml: |
    filter nks_oppgave_dag_hist [begrenset]:
      where: dato > CURRENT_DATE() - 7

    filter nks_oppgave_dag_hist [begrenset]:
      where: dato > CURRENT_DATE() - 7
  
   checks for innsyn_oppgave_dag_hist [begrenset]:
      - freshness(dato) < 1d:
          name: "Sjekker om data er mer enn ett døgn gamle"

    checks for innsyn_oppgave_dag_hist [begrenset]:
      - freshness(dato) < 1d:
          name: "Sjekker om data er mer enn ett døgn gamle"

  boost_data.yaml: |
    filter boost_chat_hour_raw [begrenset]:
      where: period > CURRENT_DATE() - 7

    filter boost_chat_human_transfer_day_raw [begrenset]:
      where: period > CURRENT_DATE() - 7

    filter boost_chat_intents_day_raw [begrenset]:
      where: period > CURRENT_DATE() - 7
     
    checks for boost_chat_hour_raw [begrenset]:
      - freshness(period) < 1d: 
          name: "Sjekker om data er mer enn ett døgn gamle"

    checks for boost_chat_human_transfer_day_raw [begrenset]:
      - freshness(period) < 1d: 
          name: "Sjekker om data er mer enn ett døgn gamle"
          
    checks for boost_chat_intents_day_raw [begrenset]:
      - freshness(period) < 1d: 
          name: "Sjekker om data er mer enn ett døgn gamle"
