apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: nks-statistikk
data:
  oppgavestatistikk.yaml: |  
    checks for nks_oppgave_dag_hist:
      - UpdatedOk > 0:
          name: "Sjekker om g책rsdagens data er p책 plass"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN MAX(dato) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM nks_oppgave_dag_hist
            WHERE dato > CURRENT_DATE() - 7

    checks for innsyn_oppgave_dag_hist:
      - UpdatedOk > 0:
          name: "Sjekker om g책rsdagens data er p책 plass"
          UpdatedOk query: |
            SELECT 
              CASE 
                WHEN MAX(dato) >= (CURRENT_DATE() -1) THEN 1 
                ELSE 0 
              END
            FROM innsyn_oppgave_dag_hist
            WHERE dato > CURRENT_DATE() - 7
