data_source oppgavestatistikk:
  type: bigquery
  project_id: nks-statistikk-prod-80c9
  dataset: oppgavestatistikk
  use_context_auth: True
  
data_source boost_data:
  type: bigquery
  project_id: nks-statistikk-prod-80c9
  dataset: boost_data
  use_context_auth: True
  
data_source sf_sto_data:
  type: bigquery
  project_id: nks-statistikk-prod-80c9
  dataset: sf_sto_data
  use_context_auth: True
  
data_source sf_chat_data:
  type: bigquery
  project_id: nks-statistikk-prod-80c9
  dataset: sf_chat_data
  use_context_auth: True
  
data_source sf_kunnskapsbase:
  type: bigquery
  project_id: nks-statistikk-prod-80c9
  dataset: sf_kunnskapsbase
  use_context_auth: True
  
data_source stillingsregistrering:
  type: bigquery
  project_id: nks-statistikk-prod-80c9
  dataset: stillingsregistrering
  use_context_auth: True
  
data_source samtalereferat_data:
  type: bigquery
  project_id: nks-statistikk-prod-80c9
  dataset: samtalereferat_data
  use_context_auth: True

data_source tastevalg_agg_mnd:
  type: bigquery
  project_id: nks-statistikk-prod-80c9
  dataset: tastevalg_agg_mnd
  use_context_auth: True