name: build, push and deploy
on: 
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'Dockerfile.dummy'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@9850be311389ca754d9a9f2280615419d738c891 # v3
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/soda-config.yaml,.nais/soda-checks.yaml,.nais/naisjob.yaml
